services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: garagedb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: garagedb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin

      KC_DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - db-network

  pgadmin:
    image: elestio/pgadmin:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - db-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - mq-network

  app:
    build:
      context: ./GarageBooking
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=garagedb;Username=admin;Password=admin
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
#      - rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - db-network
      - mq-network

  payment-app:
    build:
      context: ./GarageBooking/PaymentApp
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    env_file:
      - ./GarageBooking/PaymentApp/.env
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/garagedb?schema=payment"
      NODE_ENV: development
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - postgres
#      - rabbitmq
    networks:
      - db-network
      - mq-network

  notification-app:
    build: 
      context: ./GarageBooking/NotificationApp
      dockerfile: Dockerfile
    env_file:
      - ./GarageBooking/NotificationApp/.env
    depends_on:
      - mq-network
volumes:
  postgres_data:

networks:
  db-network:
    driver: bridge
  mq-network:
    driver: bridge
